### ISSUE TITLE
Getting negative and NaN values in confidence scores

### ISSUE THREAD

**Issue by kris314** [lluisgomez/TextProposals#2]
Hi,

I am getting all negative values in score predicted by the proposal code. Also there are many NaN values. Am I doing something wrong which results this?

Thanks,
kris

**Comment by lluisgomez** [comment]
@kris314 , The negative values are ok. As far as we have a ranking of the proposals we don't care if the score is positive or negative. Since the object proposals evaluation framework sorts proposals in ascending order (i.e. better proposals must have smaller rank) we multiply probabilities by -1 in main.cpp line 177. Doing (1-p) would be more intuitive but since we also have other scoring measures, not probabilities in the range [0,1], the easy way is to work with negative values here.

What is not normal at all are the NaN values. Are you sure to be using a clean clone of the repository? I remember having NaN values when using an old version of the code in combination with the new Boost model (trained_boost_groups.xml). In case you are sure to be working with a clean repo clone and still have NaNs around please send details on how to reproduce them. Thanks!

**Comment by kris314** [comment]
Thanks Gomez. The issue was due to Old version. Now I am getting the correct values.
